backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "content"
    label: "Περιεχόμενο"
    files:
      - label: "Αρχική"
        name: "index"
        file: "index.md"
        fields:
          - label: "Κείμενο"
            name: "body"
            widget: "markdown"
